import { Router } from "express";
import { v4 as uuid } from "uuid";
import { z } from "zod";
import { col, nowIso, orderItemsCol, presentationsCol } from "../db/firestore";
import { requireAuth, AuthedRequest } from "../middleware/auth";
export const ordersRouter = Router(); ordersRouter.use(requireAuth);
const item = z.object({ productId:z.string(), presentationId:z.string(), quantity:z.number().int().positive() });
const schema = z.object({ idempotencyKey:z.string().min(1), workDayId:z.string(), clientId:z.string(), paymentCondition:z.string().default("Contado 48h"), taxRatePermille:z.number().int().nonnegative().default(0), items:z.array(item).min(1) });
function serial(id:string,d:any,items:any[]){return { id, idempotency_key:d.idempotencyKey, work_day_id:d.workDayId,user_id:d.userId,client_id:d.clientId,payment_condition:d.paymentCondition,subtotal_cents:d.subtotalCents,tax_cents:d.taxCents,total_cents:d.totalCents,item_count:d.itemCount,status:d.status,sync_status:"synced",created_at:d.createdAt,updated_at:d.updatedAt,items};}
async function full(id:string){const d=await col.orders.doc(id).get();if(!d.exists)return null;const it=await orderItemsCol(id).get();return serial(id,d.data(),it.docs.map(x=>({id:x.id,...x.data()})));}
async function make(items:z.infer<typeof item>[]){const out:any[]=[];for(const x of items){const p=await col.products.doc(x.productId).get(), q=await presentationsCol(x.productId).doc(x.presentationId).get(); if(!p.exists||p.data()?.active===false||!q.exists||q.data()?.active===false) throw Error("Producto o presentación no encontrados o inactivos.");const a=p.data()!,b=q.data()!;if(b.productId!==x.productId)throw Error("La presentación no pertenece a este producto.");out.push({id:uuid(),product_id:x.productId,presentation_id:x.presentationId,product_name_snapshot:a.name,sku_snapshot:a.sku,presentation_name_snapshot:b.name,unit_equivalence_snapshot:b.unitEquivalence,unit_price_cents_snapshot:b.priceCents,quantity:x.quantity,subtotal_cents:b.priceCents*x.quantity});}return out;}
async function totals(w:string){const s=await col.orders.where("workDayId","==",w).get(),a=s.docs.map(x=>x.data()).filter(x=>x.status!=="cancelled");await col.workDays.doc(w).update({orderCount:a.length,totalCents:a.reduce((n,x)=>n+x.totalCents,0),updatedAt:nowIso()});}
ordersRouter.post("/",async(req:AuthedRequest,res)=>{const r=schema.safeParse(req.body);if(!r.success)return res.status(400).json({error:"Datos inválidos",details:r.error.flatten()});const d=r.data,old=await col.orders.where("idempotencyKey","==",d.idempotencyKey).limit(1).get();if(!old.empty)return res.json({order:await full(old.docs[0].id),deduped:true});const wd=await col.workDays.doc(d.workDayId).get(),cl=await col.clients.doc(d.clientId).get();if(!wd.exists)return res.status(404).json({error:"Jornada no encontrada."});if(wd.data()?.status==="closed")return res.status(409).json({error:"No se puede agregar una preventa a una jornada cerrada."});if(!cl.exists||cl.data()?.active===false)return res.status(400).json({error:"Cliente inválido o inactivo."});try{const items=await make(d.items),sub=items.reduce((n,x)=>n+x.subtotal_cents,0),tax=Math.round(sub*d.taxRatePermille/1000),id=uuid(),ts=nowIso(),batch=col.orders.firestore.batch();batch.set(col.orders.doc(id),{...d,userId:req.userId,subtotalCents:sub,taxCents:tax,totalCents:sub+tax,itemCount:items.reduce((n,x)=>n+x.quantity,0),status:"active",createdAt:ts,updatedAt:ts});items.forEach(x=>batch.set(orderItemsCol(id).doc(x.id),x));await batch.commit();await totals(d.workDayId);res.status(201).json({order:await full(id)});}catch(e:any){res.status(400).json({error:e.message});}});
ordersRouter.get("/:id",async(req,res)=>{const o=await full(req.params.id);if(!o)return res.status(404).json({error:"Preventa no encontrada."});res.json({order:o});});
ordersRouter.put("/:id",async(req,res)=>{const parsed=schema.omit({idempotencyKey:true,workDayId:true,clientId:true}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Datos inválidos",details:parsed.error.flatten()});const ref=col.orders.doc(req.params.id),old=await ref.get();if(!old.exists)return res.status(404).json({error:"Preventa no encontrada."});const order=old.data()!,wd=await col.workDays.doc(order.workDayId).get();if(wd.data()?.status==="closed")return res.status(409).json({error:"No se puede editar una preventa de una jornada cerrada."});try{const d=parsed.data,items=await make(d.items),sub=items.reduce((n,x)=>n+x.subtotal_cents,0),tax=Math.round(sub*d.taxRatePermille/1000),previous=await orderItemsCol(ref.id).get(),batch=col.orders.firestore.batch();previous.docs.forEach(x=>batch.delete(x.ref));items.forEach(x=>batch.set(orderItemsCol(ref.id).doc(x.id),x));batch.update(ref,{paymentCondition:d.paymentCondition,taxRatePermille:d.taxRatePermille,subtotalCents:sub,taxCents:tax,totalCents:sub+tax,itemCount:items.reduce((n,x)=>n+x.quantity,0),updatedAt:nowIso()});await batch.commit();await totals(order.workDayId);res.json({order:await full(ref.id)});}catch(e:any){res.status(400).json({error:e.message});}});
ordersRouter.post("/:id/cancel",async(req,res)=>{const r=col.orders.doc(req.params.id),d=await r.get();if(!d.exists)return res.status(404).json({error:"Preventa no encontrada."});const w=await col.workDays.doc(d.data()!.workDayId).get();if(w.data()?.status==="closed")return res.status(409).json({error:"No se puede cancelar una preventa de una jornada cerrada."});await r.update({status:"cancelled",updatedAt:nowIso()});await totals(d.data()!.workDayId);res.json({ok:true});});
