import { Router } from "express";
import { v4 as uuid } from "uuid";
import { col, nowIso } from "../db/firestore";
import { requireAuth, AuthedRequest } from "../middleware/auth";

export const workdaysRouter = Router();
workdaysRouter.use(requireAuth);
function today() { const p = new Intl.DateTimeFormat("en-US", { timeZone: "America/La_Paz", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const v = (t: string) => p.find(x => x.type === t)?.value; return `${v("year")}-${v("month")}-${v("day")}`; }
function serial(id: string, d: any) { return { id, user_id: d.userId, work_date: d.workDate, status: d.status, order_count: d.orderCount ?? 0, total_cents: d.totalCents ?? 0, created_at: d.createdAt, closed_at: d.closedAt ?? null }; }
async function recalc(id: string) { const orders = (await col.orders.where("workDayId", "==", id).get()).docs.map(d => d.data()).filter(d => d.status !== "cancelled"); const total = orders.reduce((n, d) => n + (d.totalCents ?? 0), 0); await col.workDays.doc(id).update({ orderCount: orders.length, totalCents: total, updatedAt: nowIso() }); return { orderCount: orders.length, totalCents: total }; }

workdaysRouter.get("/current", async (req: AuthedRequest, res) => { const date = today(); const result = await col.workDays.where("userId", "==", req.userId).where("workDate", "==", date).where("status", "==", "open").limit(1).get(); let ref = result.docs[0]?.ref; if (!ref) { ref = col.workDays.doc(uuid()); const ts = nowIso(); await ref.set({ userId: req.userId, workDate: date, status: "open", orderCount: 0, totalCents: 0, createdAt: ts, updatedAt: ts }); } const doc = await ref.get(); res.json({ workDay: serial(doc.id, doc.data()!) }); });
workdaysRouter.get("/history", async (req: AuthedRequest, res) => { const s = await col.workDays.where("userId", "==", req.userId).where("status", "==", "closed").get(); res.json({ workDays: s.docs.map(d => serial(d.id, d.data())).sort((a,b) => b.work_date.localeCompare(a.work_date)) }); });
workdaysRouter.get("/:id/orders", async (req, res) => { const s = await col.orders.where("workDayId", "==", req.params.id).get(); const orders = await Promise.all(s.docs.filter(d => d.data().status !== "cancelled").map(async d => { const c = await col.clients.doc(d.data().clientId).get(); return { id: d.id, ...d.data(), client_id: d.data().clientId, work_day_id: d.data().workDayId, business_name: c.data()?.businessName ?? "", neighborhood_id: c.data()?.neighborhoodId ?? null }; })); res.json({ orders }); });
workdaysRouter.delete("/:id", async (req: AuthedRequest, res) => { const ref = col.workDays.doc(req.params.id), d = await ref.get(); if (!d.exists || d.data()?.userId !== req.userId || d.data()?.status !== "closed") return res.status(404).json({ error: "Registro histórico no encontrado." }); const orders = await col.orders.where("workDayId", "==", ref.id).get(); const batch = col.workDays.firestore.batch(); orders.docs.forEach(o => batch.delete(o.ref)); batch.delete(ref); await batch.commit(); res.json({ ok: true }); });
workdaysRouter.post("/:id/close", async (req: AuthedRequest, res) => { if (req.body?.confirmation !== "CONFIRMAR") return res.status(400).json({ error: 'Debes escribir exactamente "CONFIRMAR" para cerrar la jornada.' }); const ref = col.workDays.doc(req.params.id), d = await ref.get(); if (!d.exists) return res.status(404).json({ error: "Jornada no encontrada." }); if (d.data()?.userId !== req.userId) return res.status(403).json({ error: "No autorizado." }); if (d.data()?.status === "closed") return res.status(409).json({ error: "La jornada ya está cerrada." }); const totals = await recalc(ref.id), ts = nowIso(); await ref.update({ status: "closed", ...totals, closedAt: ts, updatedAt: ts }); res.json({ workDay: serial(ref.id, { ...d.data(), status: "closed", ...totals, closedAt: ts }) }); });
